version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: postgres_siestai
    environment:
      POSTGRES_DB: siestai_dev
      POSTGRES_USER: siestai_user
      POSTGRES_PASSWORD: siestai_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/postgres/init:/docker-entrypoint-initdb.d
      - ./.docker/postgres/conf:/etc/postgresql/conf.d
    networks:
      - siestai_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siestai_user -d siestai_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  neo4j:
    image: neo4j:latest
    container_name: neo4j_siestai
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
    environment:
        NEO4J_AUTH: neo4j/password
        NEO4J_apoc_export_file_enabled: "true"
        NEO4J_apoc_import_file_enabled: "true"
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - siestai_network
    restart: always

  nats:
    image: nats
    command:
      - "-js"
    volumes:
      - .user/.data:/tmp/nats/jetstream
    restart: unless-stopped
    ports:
      - "4225:4222"
      - "8225:8222"
      - "6225:6222"

volumes:
  postgres_data:
    driver: local
    
networks:
  siestai_network:
    driver: bridge