[project]
name = "siestai"
version = "0.1.0"
description = "Siestai is a tool for creating and managing your AI agents."
authors = [
    { name = "Orhan Ors", email = "orhanors97@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
